// Define difficulty options
export const DIFFICULTY_OPTIONS = [
  "CP",
  "SAA",
  "DEV",
  "OPS",
  "PRO",
  "TF",
  "AzAA",
  "AzSEA",
  "AzNEA",
  "AzDSA",
  "AzDEA",
  "DevSecOps",
  "GenAI-Easy",
  "GenAI-Moderate"
];

// Define category options based on AWS exam categories
export const CATEGORY_OPTIONS = [
  "Compute",
  "Analytics",
  "Storage",
  "Database",
  "Networking",
  "Security",
  "Disaster Recovery & Resilience",
  "Cost Optimization",
  "Application Integration",
  "GenAI",
  "Serverless",
  "Migration",
  "Machine Learning",
  "IAM",
  "Containers",
  "Monitoring",
  "Developer Tools",
  "Management & Governance",
  "End User Computing",
  "Quantum Technologies",
  "General",
  "Other",
  "Terraform",
  "DevOps",
  "SecOps",
  "GitOps",
];
